# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-24 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=20, null=True, verbose_name='WRITER'),
        ),
    ]
