# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-24 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboard1', '0002_post_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
