# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import myboard1.models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard1', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_c', models.CharField(max_length=20, verbose_name='WRITER_C')),
                ('comment', models.TextField(verbose_name='COMMENT')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('post', models.ForeignKey(on_delete=myboard1.models.Post, to='myboard1.Post')),
            ],
        ),
    ]
