# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-26 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import myboard1.models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard1', '0005_auto_20190626_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='COMMENT_DATE')),
                ('comment_contents', models.CharField(max_length=200, verbose_name='COMMENT_CONTENTS')),
                ('comment_writer', models.CharField(max_length=20, null=True, verbose_name='COMMENT_WRITER')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=myboard1.models.Post, related_name='comments', to='myboard1.Post'),
        ),
    ]
