# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-26 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myboard1', '0006_auto_20190626_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myboard1.Post'),
        ),
    ]
